# 🧠 The Mind of a Model
# Day 2: Data Understanding + Cleaning

In [ ]:
import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/Aeshwa-Kachhadiya/The-mind-of-a-model/main/dataset/linkedin_post_performance.xlsx'

df = pd.read_excel(url)
print('✅ Dataset loaded!')

✅ Dataset loaded!

In [ ]:
# Shape of the dataset
print('SHAPE:')
df.shape

SHAPE:

(300, 20)

In [ ]:
# First 5 rows
print('FIRST LOOK:')
df.head()

FIRST LOOK:

,word_count,has_image,has_video,has_carousel,has_hashtags,hashtag_count,has_question,has_emoji,topic_category,posting_day,posting_hour,is_weekend,account_followers,account_age_months,posting_frequency,likes_first_hour,comments_first_hour,shares_first_hour,impressions_first_hour,went_viral
0,152.0,Yes,No,No,Yes,6,Yes,Yes,Tech,Wednesday,20,No,5822.0,21,1,185.0,48,21,1889.0,Yes
1,485.0,No,No,No,Yes,8,Yes,No,Motivation,Thursday,10,No,4544.0,59,13,98.0,30,5,3726.0,No
2,398.0,Yes,Yes,No,Yes,7,No,Yes,Tech,Tuesday,12,No,7718.0,56,2,2.0,28,2,116.0,No
3,320.0,Yes,No,No,Yes,9,No,Yes,ML,Saturday,4,Yes,4047.0,22,2,196.0,4,12,4448.0,Yes
4,156.0,No,Yes,Yes,No,0,No,Yes,Personal,Monday,0,No,1776.0,36,3,84.0,24,15,564.0,No

In [ ]:
# Data types
print('DATA TYPES:')
df.dtypes

DATA TYPES:

word_count                float64
has_image                  object
has_video                  object
has_carousel               object
has_hashtags               object
hashtag_count               int64
has_question               object
has_emoji                  object
topic_category             object
posting_day                object
posting_hour                int64
is_weekend                 object
account_followers         float64
account_age_months          int64
posting_frequency           int64
likes_first_hour          float64
comments_first_hour         int64
shares_first_hour           int64
impressions_first_hour    float64
went_viral                 object
dtype: object

In [ ]:
# Check missing values
print('MISSING VALUES:')
df.isnull().sum()

MISSING VALUES:

word_count                10
has_image                  0
has_video                  0
has_carousel               0
has_hashtags               0
hashtag_count              0
has_question               0
has_emoji                  0
topic_category             0
posting_day                0
posting_hour               0
is_weekend                 0
account_followers         20
account_age_months         0
posting_frequency          0
likes_first_hour          15
comments_first_hour        0
shares_first_hour          0
impressions_first_hour    12
went_viral                 0
dtype: int64

In [ ]:
# Statistical summary
print('STATISTICAL SUMMARY:')
df.describe()

STATISTICAL SUMMARY:

,word_count,hashtag_count,posting_hour,account_followers,account_age_months,posting_frequency,likes_first_hour,comments_first_hour,shares_first_hour,impressions_first_hour
count,290.000000,300.000000,300.00000,280.000000,300.000000,300.000000,285.000000,300.000000,300.000000,288.000000
mean,276.555172,3.483333,11.43000,6043.717857,31.790000,7.890000,148.624561,25.393333,14.446667,3006.975694
std,124.410049,3.220397,6.71332,14773.461185,17.172913,4.155574,552.585672,14.492714,8.266900,5919.588487
min,51.000000,0.000000,0.00000,0.000000,1.000000,1.000000,2.000000,0.000000,0.000000,111.000000
25%,177.250000,0.000000,6.00000,2704.500000,17.750000,4.000000,54.000000,14.000000,8.000000,1368.750000
50%,274.000000,3.000000,11.00000,4463.000000,33.000000,8.000000,107.000000,25.000000,14.000000,2676.500000
75%,385.250000,6.250000,17.00000,7341.000000,47.000000,12.000000,156.000000,38.250000,22.000000,4081.250000
max,498.000000,9.000000,23.00000,200000.000000,59.000000,14.000000,8000.000000,49.000000,29.000000,100000.000000

In [ ]:
# Target variable distribution
print('TARGET VARIABLE DISTRIBUTION:')
df['went_viral'].value_counts()

TARGET VARIABLE DISTRIBUTION:

went_viral
No     210
Yes     90
Name: count, dtype: int64

In [ ]:
# Handle missing values
# Fill numerical columns with median
numerical_cols = ['word_count', 'account_followers',
                  'likes_first_hour', 'impressions_first_hour']

for col in numerical_cols:
    median_value = df[col].median()
    df[col].fillna(median_value, inplace=True)

print('AFTER FILLING MISSING VALUES:')
print(df.isnull().sum())

AFTER FILLING MISSING VALUES:
word_count                0
has_image                 0
has_video                 0
has_carousel              0
has_hashtags              0
hashtag_count             0
has_question              0
has_emoji                 0
topic_category            0
posting_day               0
posting_hour              0
is_weekend                0
account_followers         0
account_age_months        0
posting_frequency         0
likes_first_hour          0
comments_first_hour       0
shares_first_hour         0
impressions_first_hour    0
went_viral                0
dtype: int64

/tmp/ipykernel_28034/3132036976.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(median_value, inplace=True)

In [ ]:
# Check and remove duplicates
print(f'Duplicate rows: {df.duplicated().sum()}')

df.drop_duplicates(inplace=True)

print(f'✅ Shape after removing duplicates: {df.shape}')

Duplicate rows: 0
✅ Shape after removing duplicates: (300, 20)

In [ ]:
# Final dataset check
print('FINAL DATASET:')
print(f'Shape: {df.shape}')
print(f'Missing values: {df.isnull().sum().sum()}')
df.head()

FINAL DATASET:
Shape: (300, 20)
Missing values: 0

,word_count,has_image,has_video,has_carousel,has_hashtags,hashtag_count,has_question,has_emoji,topic_category,posting_day,posting_hour,is_weekend,account_followers,account_age_months,posting_frequency,likes_first_hour,comments_first_hour,shares_first_hour,impressions_first_hour,went_viral
0,152.0,Yes,No,No,Yes,6,Yes,Yes,Tech,Wednesday,20,No,5822.0,21,1,185.0,48,21,1889.0,Yes
1,485.0,No,No,No,Yes,8,Yes,No,Motivation,Thursday,10,No,4544.0,59,13,98.0,30,5,3726.0,No
2,398.0,Yes,Yes,No,Yes,7,No,Yes,Tech,Tuesday,12,No,7718.0,56,2,2.0,28,2,116.0,No
3,320.0,Yes,No,No,Yes,9,No,Yes,ML,Saturday,4,Yes,4047.0,22,2,196.0,4,12,4448.0,Yes
4,156.0,No,Yes,Yes,No,0,No,Yes,Personal,Monday,0,No,1776.0,36,3,84.0,24,15,564.0,No